# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c31.03.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:1:03-0 --bf-size 256 --request-size 3 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c31.03.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:1:03-1 --bf-size 256 --request-size 3 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c31.04.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:1:04-0 --bf-size 256 --request-size 4 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c31.04.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:1:04-1 --bf-size 256 --request-size 4 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c31.05.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:1:05-0 --bf-size 256 --request-size 5 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c31.05.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:1:05-1 --bf-size 256 --request-size 5 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c31.10.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:1:10-0 --bf-size 256 --request-size 10 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c31.10.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:1:10-1 --bf-size 256 --request-size 10 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c31.15.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:1:15-0 --bf-size 256 --request-size 15 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c31.15.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:1:15-1 --bf-size 256 --request-size 15 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c33.03.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:3:03-0 --bf-size 256 --request-size 3 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c33.03.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:3:03-1 --bf-size 256 --request-size 3 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c33.04.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:3:04-0 --bf-size 256 --request-size 4 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c33.04.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:3:04-1 --bf-size 256 --request-size 4 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c33.05.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:3:05-0 --bf-size 256 --request-size 5 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c33.05.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:3:05-1 --bf-size 256 --request-size 5 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c33.10.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:3:10-0 --bf-size 256 --request-size 10 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c33.10.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:3:10-1 --bf-size 256 --request-size 10 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c33.15.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:3:15-0 --bf-size 256 --request-size 15 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong-full/c33.15.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label SF:3:15-1 --bf-size 256 --request-size 15 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose

# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c31.03.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:1:03-0 --bf-size 256 --request-size 3 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c31.03.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:1:03-1 --bf-size 256 --request-size 3 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c31.04.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:1:04-0 --bf-size 256 --request-size 4 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c31.04.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:1:04-1 --bf-size 256 --request-size 4 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c31.05.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:1:05-0 --bf-size 256 --request-size 5 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c31.05.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:1:05-1 --bf-size 256 --request-size 5 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c31.10.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:1:10-0 --bf-size 256 --request-size 10 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c31.10.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:1:10-1 --bf-size 256 --request-size 10 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c31.15.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:1:15-0 --bf-size 256 --request-size 15 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c31.15.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:1:15-1 --bf-size 256 --request-size 15 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c33.03.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:3:03-0 --bf-size 256 --request-size 3 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c33.03.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:3:03-1 --bf-size 256 --request-size 3 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c33.04.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:3:04-0 --bf-size 256 --request-size 4 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c33.04.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:3:04-1 --bf-size 256 --request-size 4 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c33.05.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:3:05-0 --bf-size 256 --request-size 5 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c33.05.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:3:05-1 --bf-size 256 --request-size 5 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c33.10.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:3:10-0 --bf-size 256 --request-size 10 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c33.10.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:3:10-1 --bf-size 256 --request-size 10 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c33.15.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:3:15-0 --bf-size 256 --request-size 15 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --verbose
# ./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/strong/c33.15.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/1e7 --output-label S:3:15-1 --bf-size 256 --request-size 15 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose

./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.03.1e5.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:05:03-1 --bf-size 256 --request-size 3 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.03.1e6.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:06:03-1 --bf-size 256 --request-size 3 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.03.1e7.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:07:03-1 --bf-size 256 --request-size 3 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.03.1e8.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:08:03-1 --bf-size 256 --request-size 3 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose

./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.04.1e5.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:05:04-1 --bf-size 256 --request-size 4 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.04.1e6.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:06:04-1 --bf-size 256 --request-size 4 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.04.1e7.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:07:04-1 --bf-size 256 --request-size 4 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.04.1e8.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:08:04-1 --bf-size 256 --request-size 4 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose

./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.05.1e5.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:05:05-1 --bf-size 256 --request-size 5 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.05.1e6.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:06:05-1 --bf-size 256 --request-size 5 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.05.1e7.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:07:05-1 --bf-size 256 --request-size 5 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.05.1e8.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:08:05-1 --bf-size 256 --request-size 5 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose

./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.10.1e5.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:05:10-1 --bf-size 256 --request-size 10 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.10.1e6.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:06:10-1 --bf-size 256 --request-size 10 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.10.1e7.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:07:10-1 --bf-size 256 --request-size 10 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose
./sanity-check --scn-file test/configs/evaluation/prefix-exclusion/scenarios/cache-distance/table-sizes/c33.10.1e8.scn --data-dir test/configs/evaluation/prefix-exclusion/data/req-sizes/table-sizes --output-label SF:08:10-1 --bf-size 256 --request-size 10 --mm-mode 1 --eh-mode 0 --resolution-mode 0 --verbose

adamiaonr@ubuntu:~/workbench/rid-analytics$ reset; gdb --args ./run-analysis --scn-file scripts/rocketfuel/topology.scn --data-dir experiments/examples/rocketfuel/test --output-label 4755:test --bf-size 192 --request-size 5 --mm-mode 0 --eh-mode 0 --resolution-mode 0 --origin-server 8 --start-router 0
